/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDGameGetResponseFees
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDGameGetResponseFees implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("feePercentage")
  private Integer feePercentage = null;

  @SerializedName("feeType")
  private String feeType = null;

  public SDGameGetResponseFees feePercentage(Integer feePercentage) {
    this.feePercentage = feePercentage;
    return this;
  }

   /**
   * The integer value of feePercentage. 
   * @return feePercentage
  **/
  @Schema(description = "The integer value of feePercentage. ")
  public Integer getFeePercentage() {
    return feePercentage;
  }

  public void setFeePercentage(Integer feePercentage) {
    this.feePercentage = feePercentage;
  }

  public SDGameGetResponseFees feeType(String feeType) {
    this.feeType = feeType;
    return this;
  }

   /**
   * The type of fee
   * @return feeType
  **/
  @Schema(description = "The type of fee")
  public String getFeeType() {
    return feeType;
  }

  public void setFeeType(String feeType) {
    this.feeType = feeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDGameGetResponseFees sdGameGetResponseFees = (SDGameGetResponseFees) o;
    return Objects.equals(this.feePercentage, sdGameGetResponseFees.feePercentage) &&
        Objects.equals(this.feeType, sdGameGetResponseFees.feeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feePercentage, feeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDGameGetResponseFees {\n");
    
    sb.append("    feePercentage: ").append(toIndentedString(feePercentage)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
