/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.stardust.coresdk.models.SDGameGetResponseFees;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * This is the data output json model
 */
@Schema(description = "This is the data output json model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDGameGetResponse implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("ownerId")
  private String ownerId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("desc")
  private String desc = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("bucketName")
  private String bucketName = null;

  @SerializedName("news")
  private String news = null;

  @SerializedName("fees")
  private List<SDGameGetResponseFees> fees = null;

  @SerializedName("props")
  private Object props = null;

  @SerializedName("testMode")
  private Boolean testMode = null;

  public SDGameGetResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Game ID Number (unsigned 32 bit integer)
   * minimum: 0
   * maximum: 2147483647
   * @return id
  **/
  @Schema(required = true, description = "Game ID Number (unsigned 32 bit integer)")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SDGameGetResponse ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Game Owner ID
   * @return ownerId
  **/
  @Schema(required = true, description = "Game Owner ID")
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  public SDGameGetResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Game name
   * @return name
  **/
  @Schema(required = true, description = "Game name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SDGameGetResponse desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Game description
   * @return desc
  **/
  @Schema(required = true, description = "Game description")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public SDGameGetResponse image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Game image
   * @return image
  **/
  @Schema(required = true, description = "Game image")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public SDGameGetResponse bucketName(String bucketName) {
    this.bucketName = bucketName;
    return this;
  }

   /**
   * Game bucket name
   * @return bucketName
  **/
  @Schema(required = true, description = "Game bucket name")
  public String getBucketName() {
    return bucketName;
  }

  public void setBucketName(String bucketName) {
    this.bucketName = bucketName;
  }

  public SDGameGetResponse news(String news) {
    this.news = news;
    return this;
  }

   /**
   * Game news
   * @return news
  **/
  @Schema(description = "Game news")
  public String getNews() {
    return news;
  }

  public void setNews(String news) {
    this.news = news;
  }

  public SDGameGetResponse fees(List<SDGameGetResponseFees> fees) {
    this.fees = fees;
    return this;
  }

  public SDGameGetResponse addFeesItem(SDGameGetResponseFees feesItem) {
    if (this.fees == null) {
      this.fees = new ArrayList<SDGameGetResponseFees>();
    }
    this.fees.add(feesItem);
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  @Schema(description = "")
  public List<SDGameGetResponseFees> getFees() {
    return fees;
  }

  public void setFees(List<SDGameGetResponseFees> fees) {
    this.fees = fees;
  }

  public SDGameGetResponse props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Game properties
   * @return props
  **/
  @Schema(description = "Game properties")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }

  public SDGameGetResponse testMode(Boolean testMode) {
    this.testMode = testMode;
    return this;
  }

   /**
   * If on test mode features are enabled. Currently in development.
   * @return testMode
  **/
  @Schema(description = "If on test mode features are enabled. Currently in development.")
  public Boolean isTestMode() {
    return testMode;
  }

  public void setTestMode(Boolean testMode) {
    this.testMode = testMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDGameGetResponse sdGameGetResponse = (SDGameGetResponse) o;
    return Objects.equals(this.id, sdGameGetResponse.id) &&
        Objects.equals(this.ownerId, sdGameGetResponse.ownerId) &&
        Objects.equals(this.name, sdGameGetResponse.name) &&
        Objects.equals(this.desc, sdGameGetResponse.desc) &&
        Objects.equals(this.image, sdGameGetResponse.image) &&
        Objects.equals(this.bucketName, sdGameGetResponse.bucketName) &&
        Objects.equals(this.news, sdGameGetResponse.news) &&
        Objects.equals(this.fees, sdGameGetResponse.fees) &&
        Objects.equals(this.props, sdGameGetResponse.props) &&
        Objects.equals(this.testMode, sdGameGetResponse.testMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ownerId, name, desc, image, bucketName, news, fees, props, testMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDGameGetResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    bucketName: ").append(toIndentedString(bucketName)).append("\n");
    sb.append("    news: ").append(toIndentedString(news)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    testMode: ").append(toIndentedString(testMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
