/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDGameMutateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDGameMutateRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("description")
  private String description = null;

  @SerializedName("news")
  private String news = null;

  @SerializedName("props")
  private Object props = null;

  @SerializedName("testMode")
  private Boolean testMode = null;

  public SDGameMutateRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The games description
   * @return description
  **/
  @Schema(description = "The games description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SDGameMutateRequest news(String news) {
    this.news = news;
    return this;
  }

   /**
   * The games news
   * @return news
  **/
  @Schema(description = "The games news")
  public String getNews() {
    return news;
  }

  public void setNews(String news) {
    this.news = news;
  }

  public SDGameMutateRequest props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Game properties
   * @return props
  **/
  @Schema(description = "Game properties")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }

  public SDGameMutateRequest testMode(Boolean testMode) {
    this.testMode = testMode;
    return this;
  }

   /**
   * Test mode will enable any test mode features. Currently in development.
   * @return testMode
  **/
  @Schema(description = "Test mode will enable any test mode features. Currently in development.")
  public Boolean isTestMode() {
    return testMode;
  }

  public void setTestMode(Boolean testMode) {
    this.testMode = testMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDGameMutateRequest sdGameMutateRequest = (SDGameMutateRequest) o;
    return Objects.equals(this.description, sdGameMutateRequest.description) &&
        Objects.equals(this.news, sdGameMutateRequest.news) &&
        Objects.equals(this.props, sdGameMutateRequest.props) &&
        Objects.equals(this.testMode, sdGameMutateRequest.testMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, news, props, testMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDGameMutateRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    news: ").append(toIndentedString(news)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    testMode: ").append(toIndentedString(testMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
