/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * The Money object representation of the balance
 */
@Schema(description = "The Money object representation of the balance")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerWalletGetResponseMonies implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("amount")
  private String amount = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  public SDPlayerWalletGetResponseMonies amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The balance in minor units. ex: 2000000 for 2 coins USDC
   * @return amount
  **/
  @Schema(description = "The balance in minor units. ex: 2000000 for 2 coins USDC")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public SDPlayerWalletGetResponseMonies currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency code associated with the amount. ex: &#x27;USDC&#x27;
   * @return currencyCode
  **/
  @Schema(description = "The currency code associated with the amount. ex: 'USDC'")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerWalletGetResponseMonies sdPlayerWalletGetResponseMonies = (SDPlayerWalletGetResponseMonies) o;
    return Objects.equals(this.amount, sdPlayerWalletGetResponseMonies.amount) &&
        Objects.equals(this.currencyCode, sdPlayerWalletGetResponseMonies.currencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currencyCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerWalletGetResponseMonies {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
