/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDPlayerMutateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerMutateRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("playerId")
  private String playerId = null;

  @SerializedName("props")
  private Object props = null;

  public SDPlayerMutateRequest playerId(String playerId) {
    this.playerId = playerId;
    return this;
  }

   /**
   * Can be found with Player/getId(s).
   * @return playerId
  **/
  @Schema(required = true, description = "Can be found with Player/getId(s).")
  public String getPlayerId() {
    return playerId;
  }

  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }

  public SDPlayerMutateRequest props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
   * @return props
  **/
  @Schema(required = true, description = "Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerMutateRequest sdPlayerMutateRequest = (SDPlayerMutateRequest) o;
    return Objects.equals(this.playerId, sdPlayerMutateRequest.playerId) &&
        Objects.equals(this.props, sdPlayerMutateRequest.props);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, props);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerMutateRequest {\n");
    
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
