/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * This is the data output json model, i.e. {\&quot;uniqueId\&quot;: \&quot;playerId\&quot;} 
 */
@Schema(description = "This is the data output json model, i.e. {\"uniqueId\": \"playerId\"} ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerGetIdsResponse implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("playerId")
  private String playerId = null;

  @SerializedName("uniqueId")
  private String uniqueId = null;

  public SDPlayerGetIdsResponse playerId(String playerId) {
    this.playerId = playerId;
    return this;
  }

   /**
   * Player ID in the form of a UUID
   * @return playerId
  **/
  @Schema(required = true, description = "Player ID in the form of a UUID")
  public String getPlayerId() {
    return playerId;
  }

  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }

  public SDPlayerGetIdsResponse uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Player ID in the form of a the game player&#x27;s internal playerId, i.e. email address, uuid
   * @return uniqueId
  **/
  @Schema(required = true, description = "Player ID in the form of a the game player's internal playerId, i.e. email address, uuid")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerGetIdsResponse sdPlayerGetIdsResponse = (SDPlayerGetIdsResponse) o;
    return Objects.equals(this.playerId, sdPlayerGetIdsResponse.playerId) &&
        Objects.equals(this.uniqueId, sdPlayerGetIdsResponse.uniqueId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, uniqueId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerGetIdsResponse {\n");
    
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
