/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.io.Serializable;
/**
 * This is the data output json model
 */
@Schema(description = "This is the data output json model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerGetAllResponse extends HashMap<String, String> implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("playerId")
  private String playerId = null;

  @SerializedName("uniqueId")
  private String uniqueId = null;

  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("lastSeen")
  private String lastSeen = null;

  @SerializedName("image")
  private String image = null;

  public SDPlayerGetAllResponse playerId(String playerId) {
    this.playerId = playerId;
    return this;
  }

   /**
   * Player ID in the form of a UUID
   * @return playerId
  **/
  @Schema(required = true, description = "Player ID in the form of a UUID")
  public String getPlayerId() {
    return playerId;
  }

  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }

  public SDPlayerGetAllResponse uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Game player&#x27;s unique ID from the game itself
   * @return uniqueId
  **/
  @Schema(required = true, description = "Game player's unique ID from the game itself")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  public SDPlayerGetAllResponse id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Game player&#x27;s ID in the database
   * @return id
  **/
  @Schema(description = "Game player's ID in the database")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public SDPlayerGetAllResponse lastSeen(String lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

   /**
   * Date and time the player was &#x27;last seen&#x27; actively participating in the game
   * @return lastSeen
  **/
  @Schema(description = "Date and time the player was 'last seen' actively participating in the game")
  public String getLastSeen() {
    return lastSeen;
  }

  public void setLastSeen(String lastSeen) {
    this.lastSeen = lastSeen;
  }

  public SDPlayerGetAllResponse image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL of image cached by Stardust
   * @return image
  **/
  @Schema(description = "URL of image cached by Stardust")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerGetAllResponse sdPlayerGetAllResponse = (SDPlayerGetAllResponse) o;
    return Objects.equals(this.playerId, sdPlayerGetAllResponse.playerId) &&
        Objects.equals(this.uniqueId, sdPlayerGetAllResponse.uniqueId) &&
        Objects.equals(this.id, sdPlayerGetAllResponse.id) &&
        Objects.equals(this.lastSeen, sdPlayerGetAllResponse.lastSeen) &&
        Objects.equals(this.image, sdPlayerGetAllResponse.image) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, uniqueId, id, lastSeen, image, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerGetAllResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
