/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * This is the data output json model
 */
@Schema(description = "This is the data output json model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerGetInventoryResponse implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("tokenId")
  private Integer tokenId = null;

  @SerializedName("amount")
  private String amount = null;

  public SDPlayerGetInventoryResponse tokenId(Integer tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Token ID
   * minimum: 0
   * maximum: 2147483647
   * @return tokenId
  **/
  @Schema(required = true, description = "Token ID")
  public Integer getTokenId() {
    return tokenId;
  }

  public void setTokenId(Integer tokenId) {
    this.tokenId = tokenId;
  }

  public SDPlayerGetInventoryResponse amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * u64 Number as String, min: 0, max: 9223372036854775807
   * @return amount
  **/
  @Schema(required = true, description = "u64 Number as String, min: 0, max: 9223372036854775807")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerGetInventoryResponse sdPlayerGetInventoryResponse = (SDPlayerGetInventoryResponse) o;
    return Objects.equals(this.tokenId, sdPlayerGetInventoryResponse.tokenId) &&
        Objects.equals(this.amount, sdPlayerGetInventoryResponse.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenId, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerGetInventoryResponse {\n");
    
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
