/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDPlayerCreateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDPlayerCreateRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("uniqueId")
  private String uniqueId = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("userData")
  private Object userData = null;

  public SDPlayerCreateRequest uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Identifier for the player
   * @return uniqueId
  **/
  @Schema(required = true, description = "Identifier for the player")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  public SDPlayerCreateRequest image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL of the player&#x27;s image
   * @return image
  **/
  @Schema(description = "URL of the player's image")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public SDPlayerCreateRequest userData(Object userData) {
    this.userData = userData;
    return this;
  }

   /**
   * Metadata about the player
   * @return userData
  **/
  @Schema(required = true, description = "Metadata about the player")
  public Object getUserData() {
    return userData;
  }

  public void setUserData(Object userData) {
    this.userData = userData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDPlayerCreateRequest sdPlayerCreateRequest = (SDPlayerCreateRequest) o;
    return Objects.equals(this.uniqueId, sdPlayerCreateRequest.uniqueId) &&
        Objects.equals(this.image, sdPlayerCreateRequest.image) &&
        Objects.equals(this.userData, sdPlayerCreateRequest.userData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueId, image, userData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDPlayerCreateRequest {\n");
    
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
