/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDTemplateCreateBulkProps
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTemplateCreateBulkProps implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("immutable")
  private Object immutable = null;

  @SerializedName("mutable")
  private Object mutable = null;

  @SerializedName("$mutable")
  private Object $mutable = null;

  public SDTemplateCreateBulkProps immutable(Object immutable) {
    this.immutable = immutable;
    return this;
  }

   /**
   * Properties for immutable on the Template
   * @return immutable
  **/
  @Schema(description = "Properties for immutable on the Template")
  public Object getImmutable() {
    return immutable;
  }

  public void setImmutable(Object immutable) {
    this.immutable = immutable;
  }

  public SDTemplateCreateBulkProps mutable(Object mutable) {
    this.mutable = mutable;
    return this;
  }

   /**
   * Properties for mutable on the Template
   * @return mutable
  **/
  @Schema(description = "Properties for mutable on the Template")
  public Object getMutable() {
    return mutable;
  }

  public void setMutable(Object mutable) {
    this.mutable = mutable;
  }

  public SDTemplateCreateBulkProps $mutable(Object $mutable) {
    this.$mutable = $mutable;
    return this;
  }

   /**
   * Properties for mutable on the Item
   * @return $mutable
  **/
  @Schema(description = "Properties for mutable on the Item")
  public Object get$Mutable() {
    return $mutable;
  }

  public void set$Mutable(Object $mutable) {
    this.$mutable = $mutable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTemplateCreateBulkProps sdTemplateCreateBulkProps = (SDTemplateCreateBulkProps) o;
    return Objects.equals(this.immutable, sdTemplateCreateBulkProps.immutable) &&
        Objects.equals(this.mutable, sdTemplateCreateBulkProps.mutable) &&
        Objects.equals(this.$mutable, sdTemplateCreateBulkProps.$mutable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(immutable, mutable, $mutable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTemplateCreateBulkProps {\n");
    
    sb.append("    immutable: ").append(toIndentedString(immutable)).append("\n");
    sb.append("    mutable: ").append(toIndentedString(mutable)).append("\n");
    sb.append("    $mutable: ").append(toIndentedString($mutable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
