/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDTemplateMutateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTemplateMutateRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("templateId")
  private Integer templateId = null;

  @SerializedName("props")
  private Object props = null;

  public SDTemplateMutateRequest templateId(Integer templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * This is the templateId returned from template/create (ex. 5)
   * minimum: 0
   * maximum: 2147483647
   * @return templateId
  **/
  @Schema(required = true, description = "This is the templateId returned from template/create (ex. 5)")
  public Integer getTemplateId() {
    return templateId;
  }

  public void setTemplateId(Integer templateId) {
    this.templateId = templateId;
  }

  public SDTemplateMutateRequest props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
   * @return props
  **/
  @Schema(description = "Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTemplateMutateRequest sdTemplateMutateRequest = (SDTemplateMutateRequest) o;
    return Objects.equals(this.templateId, sdTemplateMutateRequest.templateId) &&
        Objects.equals(this.props, sdTemplateMutateRequest.props);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, props);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTemplateMutateRequest {\n");
    
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
