/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDTemplateGetTokensResponsePlayer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTemplateGetTokensResponsePlayer implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("id")
  private String id = null;

  @SerializedName("uniqueId")
  private String uniqueId = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("deletedAt")
  private String deletedAt = null;

  public SDTemplateGetTokensResponsePlayer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Player ID in the form of a UUID
   * @return id
  **/
  @Schema(required = true, description = "Player ID in the form of a UUID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SDTemplateGetTokensResponsePlayer uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Player ID in the form of a the game owner&#x27;s internal playerId, i.e. email address
   * @return uniqueId
  **/
  @Schema(required = true, description = "Player ID in the form of a the game owner's internal playerId, i.e. email address")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  public SDTemplateGetTokensResponsePlayer image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL of image cached by Stardust
   * @return image
  **/
  @Schema(description = "URL of image cached by Stardust")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public SDTemplateGetTokensResponsePlayer deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Timestamp of when a player was deleted
   * @return deletedAt
  **/
  @Schema(description = "Timestamp of when a player was deleted")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTemplateGetTokensResponsePlayer sdTemplateGetTokensResponsePlayer = (SDTemplateGetTokensResponsePlayer) o;
    return Objects.equals(this.id, sdTemplateGetTokensResponsePlayer.id) &&
        Objects.equals(this.uniqueId, sdTemplateGetTokensResponsePlayer.uniqueId) &&
        Objects.equals(this.image, sdTemplateGetTokensResponsePlayer.image) &&
        Objects.equals(this.deletedAt, sdTemplateGetTokensResponsePlayer.deletedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uniqueId, image, deletedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTemplateGetTokensResponsePlayer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
