/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.stardust.coresdk.models.SDTemplateGetTokensResponsePlayer;
import gg.stardust.coresdk.models.SDTemplateGetTokensResponseToken;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * Token data
 */
@Schema(description = "Token data")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTemplateGetTokensResponse implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("token")
  private SDTemplateGetTokensResponseToken token = null;

  @SerializedName("player")
  private SDTemplateGetTokensResponsePlayer player = null;

  public SDTemplateGetTokensResponse token(SDTemplateGetTokensResponseToken token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @Schema(required = true, description = "")
  public SDTemplateGetTokensResponseToken getToken() {
    return token;
  }

  public void setToken(SDTemplateGetTokensResponseToken token) {
    this.token = token;
  }

  public SDTemplateGetTokensResponse player(SDTemplateGetTokensResponsePlayer player) {
    this.player = player;
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @Schema(required = true, description = "")
  public SDTemplateGetTokensResponsePlayer getPlayer() {
    return player;
  }

  public void setPlayer(SDTemplateGetTokensResponsePlayer player) {
    this.player = player;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTemplateGetTokensResponse sdTemplateGetTokensResponse = (SDTemplateGetTokensResponse) o;
    return Objects.equals(this.token, sdTemplateGetTokensResponse.token) &&
        Objects.equals(this.player, sdTemplateGetTokensResponse.player);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, player);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTemplateGetTokensResponse {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
