/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.stardust.coresdk.models.SDTokenMintBulkTokenObject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * SDTokenMintBulkRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTokenMintBulkRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("playerId")
  private String playerId = null;

  @SerializedName("tokenObjects")
  private List<SDTokenMintBulkTokenObject> tokenObjects = new ArrayList<SDTokenMintBulkTokenObject>();

  public SDTokenMintBulkRequest playerId(String playerId) {
    this.playerId = playerId;
    return this;
  }

   /**
   * The Player&#x27;s id, can be found with Player/getId(s). The player ID that was returned from player/create (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
   * @return playerId
  **/
  @Schema(required = true, description = "The Player's id, can be found with Player/getId(s). The player ID that was returned from player/create (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)")
  public String getPlayerId() {
    return playerId;
  }

  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }

  public SDTokenMintBulkRequest tokenObjects(List<SDTokenMintBulkTokenObject> tokenObjects) {
    this.tokenObjects = tokenObjects;
    return this;
  }

  public SDTokenMintBulkRequest addTokenObjectsItem(SDTokenMintBulkTokenObject tokenObjectsItem) {
    this.tokenObjects.add(tokenObjectsItem);
    return this;
  }

   /**
   * array of Token objects
   * @return tokenObjects
  **/
  @Schema(required = true, description = "array of Token objects")
  public List<SDTokenMintBulkTokenObject> getTokenObjects() {
    return tokenObjects;
  }

  public void setTokenObjects(List<SDTokenMintBulkTokenObject> tokenObjects) {
    this.tokenObjects = tokenObjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTokenMintBulkRequest sdTokenMintBulkRequest = (SDTokenMintBulkRequest) o;
    return Objects.equals(this.playerId, sdTokenMintBulkRequest.playerId) &&
        Objects.equals(this.tokenObjects, sdTokenMintBulkRequest.tokenObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, tokenObjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTokenMintBulkRequest {\n");
    
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    tokenObjects: ").append(toIndentedString(tokenObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
