/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDTokenMutateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTokenMutateRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("tokenId")
  private Integer tokenId = null;

  @SerializedName("props")
  private Object props = null;

  @SerializedName("publicMetadata")
  private Object publicMetadata = null;

  public SDTokenMutateRequest tokenId(Integer tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Specifies which tokenId you want to manipulate (ex. 11)
   * minimum: 0
   * maximum: 2147483647
   * @return tokenId
  **/
  @Schema(required = true, description = "Specifies which tokenId you want to manipulate (ex. 11)")
  public Integer getTokenId() {
    return tokenId;
  }

  public void setTokenId(Integer tokenId) {
    this.tokenId = tokenId;
  }

  public SDTokenMutateRequest props(Object props) {
    this.props = props;
    return this;
  }

   /**
   * Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
   * @return props
  **/
  @Schema(required = true, description = "Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})")
  public Object getProps() {
    return props;
  }

  public void setProps(Object props) {
    this.props = props;
  }

  public SDTokenMutateRequest publicMetadata(Object publicMetadata) {
    this.publicMetadata = publicMetadata;
    return this;
  }

   /**
   * Returned to marketplaces as token metadata
   * @return publicMetadata
  **/
  @Schema(description = "Returned to marketplaces as token metadata")
  public Object getPublicMetadata() {
    return publicMetadata;
  }

  public void setPublicMetadata(Object publicMetadata) {
    this.publicMetadata = publicMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTokenMutateRequest sdTokenMutateRequest = (SDTokenMutateRequest) o;
    return Objects.equals(this.tokenId, sdTokenMutateRequest.tokenId) &&
        Objects.equals(this.props, sdTokenMutateRequest.props) &&
        Objects.equals(this.publicMetadata, sdTokenMutateRequest.publicMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenId, props, publicMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTokenMutateRequest {\n");
    
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    publicMetadata: ").append(toIndentedString(publicMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
