/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * Internal metadata
 */
@Schema(description = "Internal metadata")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTokenMintBulkTokenObjectProps implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("mutable")
  private Object mutable = null;

  @SerializedName("immutable")
  private Object immutable = null;

  public SDTokenMintBulkTokenObjectProps mutable(Object mutable) {
    this.mutable = mutable;
    return this;
  }

   /**
   * Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
   * @return mutable
  **/
  @Schema(required = true, description = "Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})")
  public Object getMutable() {
    return mutable;
  }

  public void setMutable(Object mutable) {
    this.mutable = mutable;
  }

  public SDTokenMintBulkTokenObjectProps immutable(Object immutable) {
    this.immutable = immutable;
    return this;
  }

   /**
   * Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
   * @return immutable
  **/
  @Schema(description = "Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})")
  public Object getImmutable() {
    return immutable;
  }

  public void setImmutable(Object immutable) {
    this.immutable = immutable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTokenMintBulkTokenObjectProps sdTokenMintBulkTokenObjectProps = (SDTokenMintBulkTokenObjectProps) o;
    return Objects.equals(this.mutable, sdTokenMintBulkTokenObjectProps.mutable) &&
        Objects.equals(this.immutable, sdTokenMintBulkTokenObjectProps.immutable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mutable, immutable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTokenMintBulkTokenObjectProps {\n");
    
    sb.append("    mutable: ").append(toIndentedString(mutable)).append("\n");
    sb.append("    immutable: ").append(toIndentedString(immutable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
