/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.stardust.coresdk.models.SDTokenMintBulkTokenObjectProps;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
/**
 * SDTokenMintBulkTokenObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-09T11:52:00.026066-08:00[America/Los_Angeles]")
public class SDTokenMintBulkTokenObject implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("templateId")
  private Integer templateId = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("props")
  private SDTokenMintBulkTokenObjectProps props = null;

  @SerializedName("publicMetadata")
  private Object publicMetadata = null;

  public SDTokenMintBulkTokenObject templateId(Integer templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * Specifies which Template you are creating an instance of (ex. 3)
   * minimum: 0
   * maximum: 2147483647
   * @return templateId
  **/
  @Schema(required = true, description = "Specifies which Template you are creating an instance of (ex. 3)")
  public Integer getTemplateId() {
    return templateId;
  }

  public void setTemplateId(Integer templateId) {
    this.templateId = templateId;
  }

  public SDTokenMintBulkTokenObject amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * u64 Number as String, min: 0, max: 9223372036854775807 (ex. \&quot;6\&quot;)
   * @return amount
  **/
  @Schema(required = true, description = "u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\")")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public SDTokenMintBulkTokenObject props(SDTokenMintBulkTokenObjectProps props) {
    this.props = props;
    return this;
  }

   /**
   * Get props
   * @return props
  **/
  @Schema(description = "")
  public SDTokenMintBulkTokenObjectProps getProps() {
    return props;
  }

  public void setProps(SDTokenMintBulkTokenObjectProps props) {
    this.props = props;
  }

  public SDTokenMintBulkTokenObject publicMetadata(Object publicMetadata) {
    this.publicMetadata = publicMetadata;
    return this;
  }

   /**
   * Returned to marketplaces as token metadata
   * @return publicMetadata
  **/
  @Schema(description = "Returned to marketplaces as token metadata")
  public Object getPublicMetadata() {
    return publicMetadata;
  }

  public void setPublicMetadata(Object publicMetadata) {
    this.publicMetadata = publicMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDTokenMintBulkTokenObject sdTokenMintBulkTokenObject = (SDTokenMintBulkTokenObject) o;
    return Objects.equals(this.templateId, sdTokenMintBulkTokenObject.templateId) &&
        Objects.equals(this.amount, sdTokenMintBulkTokenObject.amount) &&
        Objects.equals(this.props, sdTokenMintBulkTokenObject.props) &&
        Objects.equals(this.publicMetadata, sdTokenMintBulkTokenObject.publicMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, amount, props, publicMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDTokenMintBulkTokenObject {\n");
    
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    publicMetadata: ").append(toIndentedString(publicMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
