/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.apis;

import gg.stardust.coresdk.models.Empty;
import gg.stardust.coresdk.models.Error;
import gg.stardust.coresdk.models.SDGameGetResponse;
import gg.stardust.coresdk.models.SDGameMutateRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GameEndpointsApi
 */
@Ignore
public class GameEndpointsApiTest {

    private final GameEndpointsApi api = new GameEndpointsApi();

    /**
     * Get Game
     *
     * Get the Details of Your Game
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gameGetGetTest() throws Exception {
        SDGameGetResponse response = api.gameGetGet();

        // TODO: test validations
    }
    /**
     * Mutate Game
     *
     * Change a games data
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gameMutatePutTest() throws Exception {
        SDGameMutateRequest body = null;
        Empty response = api.gameMutatePut(body);

        // TODO: test validations
    }
}
