/*
 * Stardust API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gg.stardust.coresdk.apis;

import gg.stardust.coresdk.models.Error;
import gg.stardust.coresdk.models.SDHealthResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for HealthEndpointsApi
 */
@Ignore
public class HealthEndpointsApiTest {

    private final HealthEndpointsApi api = new HealthEndpointsApi();

    /**
     * Get Health
     *
     * Get system health info
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void healthGetTest() throws Exception {
        SDHealthResponse response = api.healthGet();

        // TODO: test validations
    }
}
